# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: fileserver.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='fileserver.proto',
  package='file_server',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x10\x66ileserver.proto\x12\x0b\x66ile_server\"\x1b\n\x0bRequestSend\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\"\x1c\n\x0eResponseStatus\x12\n\n\x02ok\x18\x01 \x01(\x08\"\x1b\n\x0bRequestFile\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x1e\n\x0eResponseStream\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\x32\x9c\x01\n\x0c\x46ileTransfer\x12\x43\n\x08SendFile\x12\x18.file_server.RequestSend\x1a\x1b.file_server.ResponseStatus(\x01\x12G\n\x0c\x44ownloadFile\x12\x18.file_server.RequestFile\x1a\x1b.file_server.ResponseStream0\x01\x62\x06proto3'
)




_REQUESTSEND = _descriptor.Descriptor(
  name='RequestSend',
  full_name='file_server.RequestSend',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='file_server.RequestSend.data', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=33,
  serialized_end=60,
)


_RESPONSESTATUS = _descriptor.Descriptor(
  name='ResponseStatus',
  full_name='file_server.ResponseStatus',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='ok', full_name='file_server.ResponseStatus.ok', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=62,
  serialized_end=90,
)


_REQUESTFILE = _descriptor.Descriptor(
  name='RequestFile',
  full_name='file_server.RequestFile',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='file_server.RequestFile.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=92,
  serialized_end=119,
)


_RESPONSESTREAM = _descriptor.Descriptor(
  name='ResponseStream',
  full_name='file_server.ResponseStream',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='file_server.ResponseStream.data', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=121,
  serialized_end=151,
)

DESCRIPTOR.message_types_by_name['RequestSend'] = _REQUESTSEND
DESCRIPTOR.message_types_by_name['ResponseStatus'] = _RESPONSESTATUS
DESCRIPTOR.message_types_by_name['RequestFile'] = _REQUESTFILE
DESCRIPTOR.message_types_by_name['ResponseStream'] = _RESPONSESTREAM
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RequestSend = _reflection.GeneratedProtocolMessageType('RequestSend', (_message.Message,), {
  'DESCRIPTOR' : _REQUESTSEND,
  '__module__' : 'fileserver_pb2'
  # @@protoc_insertion_point(class_scope:file_server.RequestSend)
  })
_sym_db.RegisterMessage(RequestSend)

ResponseStatus = _reflection.GeneratedProtocolMessageType('ResponseStatus', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSESTATUS,
  '__module__' : 'fileserver_pb2'
  # @@protoc_insertion_point(class_scope:file_server.ResponseStatus)
  })
_sym_db.RegisterMessage(ResponseStatus)

RequestFile = _reflection.GeneratedProtocolMessageType('RequestFile', (_message.Message,), {
  'DESCRIPTOR' : _REQUESTFILE,
  '__module__' : 'fileserver_pb2'
  # @@protoc_insertion_point(class_scope:file_server.RequestFile)
  })
_sym_db.RegisterMessage(RequestFile)

ResponseStream = _reflection.GeneratedProtocolMessageType('ResponseStream', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSESTREAM,
  '__module__' : 'fileserver_pb2'
  # @@protoc_insertion_point(class_scope:file_server.ResponseStream)
  })
_sym_db.RegisterMessage(ResponseStream)



_FILETRANSFER = _descriptor.ServiceDescriptor(
  name='FileTransfer',
  full_name='file_server.FileTransfer',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=154,
  serialized_end=310,
  methods=[
  _descriptor.MethodDescriptor(
    name='SendFile',
    full_name='file_server.FileTransfer.SendFile',
    index=0,
    containing_service=None,
    input_type=_REQUESTSEND,
    output_type=_RESPONSESTATUS,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='DownloadFile',
    full_name='file_server.FileTransfer.DownloadFile',
    index=1,
    containing_service=None,
    input_type=_REQUESTFILE,
    output_type=_RESPONSESTREAM,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_FILETRANSFER)

DESCRIPTOR.services_by_name['FileTransfer'] = _FILETRANSFER

# @@protoc_insertion_point(module_scope)
